export enum IAPI_AUTH_ERROR {
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    INVALID_TOKEN = 'INVALID_TOKEN',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    NULL = 'NULL',
    WRONG_PASSWORD = 'WRONG_PASSWORD',
    DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
}

export enum IAPI_SEARCH_ERROR {
    NO_RESULT = 'NO_RESULT',
    NULL = 'NULL',

}